// "Ronaldo vs Jesus" narration, split into on-screen caption chunks.
// `at` is seconds from the START OF THE SCENE. A chunk stays up until the next
// chunk (or the end of the scene). Wrap words in *stars* to highlight them gold.
// Captions use the voiceover text verbatim, so they double as the VO script.
// The video is silent: timings are estimates for a later voiceover.
import type { ScriptLine } from "../lib/timeline";

export const RVJ_SCRIPT = {
  hook: [
    { at: 0.3, text: "A week ago, the *greatest goalscorer* in football history" },
    { at: 3.6, text: "walked out on *his country.*" },
    { at: 5.6, text: "He got on a *private jet*" },
    { at: 7.6, text: "and promised to tell *the truth.*" },
    { at: 10.4, text: "*Last night,*" },
    { at: 11.6, text: "he did." },
  ],
  plan: [
    { at: 0.3, text: "After the World Cup, Ronaldo was *ready to quit.*" },
    { at: 3.4, text: "He'd even written a *goodbye letter.*" },
    { at: 6.0, text: "But on the flight home," },
    { at: 7.6, text: "the federation *begged him to stay,*" },
    { at: 10.2, text: "and asked who should be *the new coach.*" },
    { at: 13.4, text: "Ronaldo backed *Jorge Jesus.*" },
    { at: 15.6, text: "His old coach from *Al-Nassr.*" },
    { at: 17.8, text: "Jesus came with *a plan:*" },
    { at: 19.8, text: "Ronaldo plays *the first match*" },
    { at: 22.4, text: "*and the last one.*" },
    { at: 24.6, text: "*Simple.*" },
  ],
  norway: [
    { at: 0.3, text: "But then, *Norway.*" },
    { at: 2.0, text: "At lunch, the coach asks:" },
    { at: 4.0, text: "can you play *30 minutes?*" },
    { at: 6.4, text: "Ronaldo says *yes.*" },
    { at: 8.0, text: "He warms up from *half-time.*" },
    { at: 10.4, text: "*Five minutes.*" },
    { at: 11.8, text: "*Twenty.*" },
    { at: 13.0, text: "*Forty.*" },
    { at: 14.4, text: "The *final whistle* blows." },
    { at: 16.4, text: "He *never steps on the pitch.*" },
    { at: 18.8, text: "In his words:" },
    { at: 20.0, text: "'The head coach had *failed to keep his word.*'" },
  ],
  deal: [
    { at: 0.3, text: "Two days later," },
    { at: 1.6, text: "they sit down and *make a deal.*" },
    { at: 4.0, text: "At his next press conference," },
    { at: 6.0, text: "the coach would *tell the truth:*" },
    { at: 8.4, text: "that this was *his plan,*" },
    { at: 10.2, text: "and benching Ronaldo after a warm-up" },
    { at: 12.6, text: "was *a mistake.*" },
    { at: 14.2, text: "They *wrote it down.*" },
    { at: 15.8, text: "*Eight points.*" },
    { at: 17.0, text: "Ronaldo *approved it.*" },
    { at: 18.6, text: "They even *hugged.*" },
    { at: 20.2, text: "The coach didn't even have to *apologize.*" },
  ],
  press: [
    { at: 0.3, text: "Then came *the press conference.*" },
    { at: 2.4, text: "Ronaldo says the coach did *the opposite:*" },
    { at: 4.8, text: "*aggressive,* high and mighty." },
    { at: 6.8, text: "Jesus told reporters *he's the coach,*" },
    { at: 8.8, text: "there was *no incident,*" },
    { at: 10.2, text: "and Ronaldo *wouldn't start* against Denmark." },
    { at: 12.6, text: "For Ronaldo, that was *promise number two, broken.*" },
    { at: 15.4, text: "He arrived at the stadium with the team," },
    { at: 17.4, text: "and *never trained.*" },
    { at: 18.8, text: "Reports say the coach and federation president" },
    { at: 21.0, text: "followed him *to the airport* to stop him." },
    { at: 23.0, text: "He got on the jet *anyway.*" },
  ],
  twist: [
    { at: 0.3, text: "But here's the part *nobody expected.*" },
    { at: 2.6, text: "Ronaldo admits walking out *was wrong.*" },
    { at: 5.0, text: "He *apologized* to his teammates," },
    { at: 7.0, text: "and asked the federation to *punish him*" },
    { at: 9.0, text: "with *no reduction,* because he's the captain." },
    { at: 11.8, text: "And he's *not retiring.*" },
    { at: 13.4, text: "After any suspension, he says" },
    { at: 15.0, text: "he's ready to play for Portugal *again.*" },
    { at: 17.0, text: "He's *21 goals* away from *1,000.*" },
  ],
  timing: [
    { at: 0.3, text: "And now, *the timing.*" },
    { at: 2.0, text: "He promised the truth *'in due course.'*" },
    { at: 4.6, text: "He picked the *exact same day*" },
    { at: 6.8, text: "Messi said *goodbye* to Argentina." },
    { at: 9.0, text: "Out of every day he could have posted," },
    { at: 11.2, text: "he chose *that one.*" },
    { at: 12.8, text: "*Coincidence?*" },
    { at: 14.2, text: "Or did Ronaldo just *steal the spotlight* one last time?" },
    { at: 17.6, text: "One legend *chose his ending.*" },
    { at: 19.6, text: "The other says he's *not done yet.*" },
    { at: 21.8, text: "So, *who's right?*" },
    { at: 23.2, text: "And was the timing *planned?*" },
    { at: 25.0, text: "Tell us in the *comments.*" },
  ],
} satisfies Record<string, ScriptLine[]>;
